# https://taskfile.dev

version: '3'


vars:
  BASE_NAME: kyushu-latest

tasks:
  #install-tilemaker:
  # need to build from source. see https://github.com/systemed/tilemaker#installing

  dl-water:
    cmds:
      - wget https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip
      - unzip water-polygons-split-4326.zip
      - mv water-polygons-split-4326/water_polygons.* tilemaker/coastline
      - rm -rf water-polygons-split-4326.zip water-polygons-split-4326/
    status:
      - test -f tilemaker/coastline/water_polygons.shp
 
  dl-pbf:
    cmds: 
      - wget -P data https://download.geofabrik.de/asia/japan/kyushu-latest.osm.pbf
    status:
      - test -f data/kyushu-latest.osm.pbf
    # or you can dowoload from https://app.protomaps.com/downloads/osm

  make-mbtiles:
    dir: tilemaker/
    deps: [dl-water, dl-pbf] # install-tilemaker
    cmds:
      - tilemaker --input ../data/{{.BASE_NAME}}.osm.pbf --output ../data/{{.BASE_NAME}}.mbtiles --config config/config-openmaptiles.json --process config/process-openmaptiles-kumejima.lua
    sources:
      - ../data/{{.BASE_NAME}}.osm.pbf
      - config/config-openmaptiles.json
      - config/process-openmaptiles-kumejima.lua
    generates:
      - ../data/{{.BASE_NAME}}.mbtiles
    method: timestamp


  install-tileserver:
    cmds:
      - pnpm install -g tileserver-gl-light
    status: 
      - tileserver-gl-light --version

  preview-mbtiles:
    deps: [make-mbtiles, install-tileserver]
    cmds:
      # `--no-cors` option does not work: see also: [link to issue]
      - tileserver-gl-light data/{{.BASE_NAME}}.mbtiles --port 8081

  install-pmtiles:
    cmds:
      - curl -sL -o - https://github.com/protomaps/go-pmtiles/releases/download/v1.8.0/go-pmtiles-1.8.0_Darwin_arm64.zip | bsdtar xf -
      - chmod +x pmtiles
    status:
      - ./pmtiles

  make-pmtiles:
    deps: [install-pmtiles, make-mbtiles]
    cmds:
      - ./pmtiles convert data/{{.BASE_NAME}}.mbtiles data/{{.BASE_NAME}}.pmtiles
    sources:
      - data/{{.BASE_NAME}}.mbtiles
    generates:
      - data/{{.BASE_NAME}}.pmtiles
    method: timestamp

  serve-pmtiles:
    deps: [make-pmtiles]
    cmds: 
      - ./pmtiles serve ./data --cors "*" --port 8080

  run-maputnik:
    cmds:
      - docker run -it --rm -p 8888:8888 maputnik/editor
      
  run-editor:
    deps: [serve-pmtiles, run-maputnik]
    cmds:
      - open -u http://localhost:8888

  install-front:
    dir: front/
    cmds:
      - pnpm install
    status:
      - test -d node_modules
    
  # see also: https://ja.vitejs.dev/guide/env-and-mode.html#env-files
  prep-front:
    deps: [install-front]
    dir: front/
    cmds:
      - cp ../data/{{.BASE_NAME}}.pmtiles public/{{.BASE_NAME}}.pmtiles
      - echo "VITE_BASE_NAME={{.BASE_NAME}}" > .env

  serve-front:
    deps: [prep-front]
    dir: front/
    cmds:
      - BASE_NAME={{.BASE_NAME}} pnpm dev
  build-front:
    deps: [prep-front]
    dir: front/
    cmds:
      - pnpm build

  preview-front:
    dir: front/
    deps: [build-front]
    cmds:
      - pnpm preview
